// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIConfig() {
  return window['go']['main']['App']['AIConfig']();
}

export function AIPromptConfig() {
  return window['go']['main']['App']['AIPromptConfig']();
}

export function AISuggest(arg1) {
  return window['go']['main']['App']['AISuggest'](arg1);
}

export function AISuggestions(arg1) {
  return window['go']['main']['App']['AISuggestions'](arg1);
}

export function AcceptAISuggestion(arg1) {
  return window['go']['main']['App']['AcceptAISuggestion'](arg1);
}

export function AccountKinds() {
  return window['go']['main']['App']['AccountKinds']();
}

export function AccountOptions() {
  return window['go']['main']['App']['AccountOptions']();
}

export function AccountantReset(arg1) {
  return window['go']['main']['App']['AccountantReset'](arg1);
}

export function AccountantSend(arg1) {
  return window['go']['main']['App']['AccountantSend'](arg1);
}

export function AccountantSession(arg1) {
  return window['go']['main']['App']['AccountantSession'](arg1);
}

export function Accounts() {
  return window['go']['main']['App']['Accounts']();
}

export function Accrue(arg1) {
  return window['go']['main']['App']['Accrue'](arg1);
}

export function ActiveContacts(arg1, arg2) {
  return window['go']['main']['App']['ActiveContacts'](arg1, arg2);
}

export function AdjustSalary(arg1) {
  return window['go']['main']['App']['AdjustSalary'](arg1);
}

export function AgingReport(arg1) {
  return window['go']['main']['App']['AgingReport'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApproveClaim(arg1) {
  return window['go']['main']['App']['ApproveClaim'](arg1);
}

export function Assets() {
  return window['go']['main']['App']['Assets']();
}

export function AttachmentPath(arg1) {
  return window['go']['main']['App']['AttachmentPath'](arg1);
}

export function Attachments(arg1) {
  return window['go']['main']['App']['Attachments'](arg1);
}

export function AuditAttachments(arg1, arg2) {
  return window['go']['main']['App']['AuditAttachments'](arg1, arg2);
}

export function AuditLog(arg1) {
  return window['go']['main']['App']['AuditLog'](arg1);
}

export function AuditSettings() {
  return window['go']['main']['App']['AuditSettings']();
}

export function Backup(arg1) {
  return window['go']['main']['App']['Backup'](arg1);
}

export function BankAccounts() {
  return window['go']['main']['App']['BankAccounts']();
}

export function BankFlows(arg1) {
  return window['go']['main']['App']['BankFlows'](arg1);
}

export function BankReconciliation(arg1) {
  return window['go']['main']['App']['BankReconciliation'](arg1);
}

export function BankRules() {
  return window['go']['main']['App']['BankRules']();
}

export function BankStats() {
  return window['go']['main']['App']['BankStats']();
}

export function Bookkeeper() {
  return window['go']['main']['App']['Bookkeeper']();
}

export function BuildPayroll(arg1) {
  return window['go']['main']['App']['BuildPayroll'](arg1);
}

export function CheckVoucher(arg1) {
  return window['go']['main']['App']['CheckVoucher'](arg1);
}

export function ChooseBookDir(arg1) {
  return window['go']['main']['App']['ChooseBookDir'](arg1);
}

export function ChooseBookFile() {
  return window['go']['main']['App']['ChooseBookFile']();
}

export function ClaimCategories() {
  return window['go']['main']['App']['ClaimCategories']();
}

export function ClaimDetail(arg1) {
  return window['go']['main']['App']['ClaimDetail'](arg1);
}

export function Claims(arg1) {
  return window['go']['main']['App']['Claims'](arg1);
}

export function Close(arg1) {
  return window['go']['main']['App']['Close'](arg1);
}

export function CloseBook() {
  return window['go']['main']['App']['CloseBook']();
}

export function Columnar(arg1) {
  return window['go']['main']['App']['Columnar'](arg1);
}

export function ColumnarAccounts() {
  return window['go']['main']['App']['ColumnarAccounts']();
}

export function ContactKinds() {
  return window['go']['main']['App']['ContactKinds']();
}

export function ContactList() {
  return window['go']['main']['App']['ContactList']();
}

export function ContactOptions() {
  return window['go']['main']['App']['ContactOptions']();
}

export function ContactUsageOf(arg1) {
  return window['go']['main']['App']['ContactUsageOf'](arg1);
}

export function Contacts(arg1) {
  return window['go']['main']['App']['Contacts'](arg1);
}

export function CreateBook(arg1) {
  return window['go']['main']['App']['CreateBook'](arg1);
}

export function CreateDemoBook(arg1) {
  return window['go']['main']['App']['CreateDemoBook'](arg1);
}

export function CurrentBook() {
  return window['go']['main']['App']['CurrentBook']();
}

export function DefaultBookDir() {
  return window['go']['main']['App']['DefaultBookDir']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteAmortization(arg1) {
  return window['go']['main']['App']['DeleteAmortization'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteDepartment(arg1) {
  return window['go']['main']['App']['DeleteDepartment'](arg1);
}

export function DeleteVoucher(arg1) {
  return window['go']['main']['App']['DeleteVoucher'](arg1);
}

export function DepartmentUsageOf(arg1) {
  return window['go']['main']['App']['DepartmentUsageOf'](arg1);
}

export function Departments() {
  return window['go']['main']['App']['Departments']();
}

export function DisposeAsset(arg1) {
  return window['go']['main']['App']['DisposeAsset'](arg1);
}

export function Employees(arg1) {
  return window['go']['main']['App']['Employees'](arg1);
}

export function ExportAuditLog(arg1, arg2) {
  return window['go']['main']['App']['ExportAuditLog'](arg1, arg2);
}

export function ExportColumnar(arg1, arg2) {
  return window['go']['main']['App']['ExportColumnar'](arg1, arg2);
}

export function ExportReconciliation(arg1, arg2) {
  return window['go']['main']['App']['ExportReconciliation'](arg1, arg2);
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function ExportSummary(arg1, arg2) {
  return window['go']['main']['App']['ExportSummary'](arg1, arg2);
}

export function ExportVATPolicies(arg1) {
  return window['go']['main']['App']['ExportVATPolicies'](arg1);
}

export function FilesDir() {
  return window['go']['main']['App']['FilesDir']();
}

export function Health(arg1) {
  return window['go']['main']['App']['Health'](arg1);
}

export function IgnoreBankFlow(arg1, arg2) {
  return window['go']['main']['App']['IgnoreBankFlow'](arg1, arg2);
}

export function ImportBankFlows(arg1) {
  return window['go']['main']['App']['ImportBankFlows'](arg1);
}

export function ImportVATPolicies(arg1) {
  return window['go']['main']['App']['ImportVATPolicies'](arg1);
}

export function InspectBackup(arg1) {
  return window['go']['main']['App']['InspectBackup'](arg1);
}

export function InsuranceSchemes() {
  return window['go']['main']['App']['InsuranceSchemes']();
}

export function InvoiceCategories() {
  return window['go']['main']['App']['InvoiceCategories']();
}

export function InvoiceRates() {
  return window['go']['main']['App']['InvoiceRates']();
}

export function InvoiceSummary(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvoiceSummary'](arg1, arg2, arg3);
}

export function Invoices(arg1) {
  return window['go']['main']['App']['Invoices'](arg1);
}

export function JudgeDeduction(arg1) {
  return window['go']['main']['App']['JudgeDeduction'](arg1);
}

export function LedgerDetail(arg1) {
  return window['go']['main']['App']['LedgerDetail'](arg1);
}

export function ListBooks() {
  return window['go']['main']['App']['ListBooks']();
}

export function MatchBankFlows() {
  return window['go']['main']['App']['MatchBankFlows']();
}

export function OpenBook(arg1) {
  return window['go']['main']['App']['OpenBook'](arg1);
}

export function OrphanAttachments() {
  return window['go']['main']['App']['OrphanAttachments']();
}

export function Overview() {
  return window['go']['main']['App']['Overview']();
}

export function PayrollRunDetail(arg1) {
  return window['go']['main']['App']['PayrollRunDetail'](arg1);
}

export function PayrollRuns() {
  return window['go']['main']['App']['PayrollRuns']();
}

export function Periods() {
  return window['go']['main']['App']['Periods']();
}

export function PostBankFlows(arg1) {
  return window['go']['main']['App']['PostBankFlows'](arg1);
}

export function PostClaim(arg1) {
  return window['go']['main']['App']['PostClaim'](arg1);
}

export function PostInvoice(arg1) {
  return window['go']['main']['App']['PostInvoice'](arg1);
}

export function PostPayroll(arg1, arg2) {
  return window['go']['main']['App']['PostPayroll'](arg1, arg2);
}

export function PreviewAIPrompt(arg1) {
  return window['go']['main']['App']['PreviewAIPrompt'](arg1);
}

export function PreviewAccountantPrompt() {
  return window['go']['main']['App']['PreviewAccountantPrompt']();
}

export function PreviewAccrual(arg1) {
  return window['go']['main']['App']['PreviewAccrual'](arg1);
}

export function PreviewClose(arg1) {
  return window['go']['main']['App']['PreviewClose'](arg1);
}

export function RejectAISuggestion(arg1) {
  return window['go']['main']['App']['RejectAISuggestion'](arg1);
}

export function RejectClaim(arg1) {
  return window['go']['main']['App']['RejectClaim'](arg1);
}

export function RemoveAttachment(arg1) {
  return window['go']['main']['App']['RemoveAttachment'](arg1);
}

export function Reopen(arg1) {
  return window['go']['main']['App']['Reopen'](arg1);
}

export function Report(arg1) {
  return window['go']['main']['App']['Report'](arg1);
}

export function ResetAIPromptConfig() {
  return window['go']['main']['App']['ResetAIPromptConfig']();
}

export function ResetVATPolicies() {
  return window['go']['main']['App']['ResetVATPolicies']();
}

export function ResignEmployee(arg1) {
  return window['go']['main']['App']['ResignEmployee'](arg1);
}

export function ResolveVATRate(arg1) {
  return window['go']['main']['App']['ResolveVATRate'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RevealBookDir(arg1) {
  return window['go']['main']['App']['RevealBookDir'](arg1);
}

export function ReverseVoucher(arg1) {
  return window['go']['main']['App']['ReverseVoucher'](arg1);
}

export function SaveAIPromptConfig(arg1) {
  return window['go']['main']['App']['SaveAIPromptConfig'](arg1);
}

export function SaveAIProvider(arg1) {
  return window['go']['main']['App']['SaveAIProvider'](arg1);
}

export function SaveAccount(arg1) {
  return window['go']['main']['App']['SaveAccount'](arg1);
}

export function SaveAmortization(arg1) {
  return window['go']['main']['App']['SaveAmortization'](arg1);
}

export function SaveAsset(arg1) {
  return window['go']['main']['App']['SaveAsset'](arg1);
}

export function SaveAuditSettings(arg1) {
  return window['go']['main']['App']['SaveAuditSettings'](arg1);
}

export function SaveBankRule(arg1) {
  return window['go']['main']['App']['SaveBankRule'](arg1);
}

export function SaveBookkeeper(arg1) {
  return window['go']['main']['App']['SaveBookkeeper'](arg1);
}

export function SaveClaim(arg1) {
  return window['go']['main']['App']['SaveClaim'](arg1);
}

export function SaveContact(arg1) {
  return window['go']['main']['App']['SaveContact'](arg1);
}

export function SaveDepartment(arg1) {
  return window['go']['main']['App']['SaveDepartment'](arg1);
}

export function SaveEmployee(arg1) {
  return window['go']['main']['App']['SaveEmployee'](arg1);
}

export function SaveInsuranceSchemes(arg1) {
  return window['go']['main']['App']['SaveInsuranceSchemes'](arg1);
}

export function SaveInvoice(arg1) {
  return window['go']['main']['App']['SaveInvoice'](arg1);
}

export function SaveVoucher(arg1) {
  return window['go']['main']['App']['SaveVoucher'](arg1);
}

export function SchemeTemplate(arg1) {
  return window['go']['main']['App']['SchemeTemplate'](arg1);
}

export function SetAccountEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAccountEnabled'](arg1, arg2);
}

export function SetBankSuggestion(arg1) {
  return window['go']['main']['App']['SetBankSuggestion'](arg1);
}

export function SetEnterpriseScale(arg1) {
  return window['go']['main']['App']['SetEnterpriseScale'](arg1);
}

export function SetVATStatus(arg1) {
  return window['go']['main']['App']['SetVATStatus'](arg1);
}

export function Statement(arg1) {
  return window['go']['main']['App']['Statement'](arg1);
}

export function SuggestBookPath(arg1) {
  return window['go']['main']['App']['SuggestBookPath'](arg1);
}

export function SuggestExportPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuggestExportPath'](arg1, arg2, arg3);
}

export function SuggestedColumnarName(arg1) {
  return window['go']['main']['App']['SuggestedColumnarName'](arg1);
}

export function SuggestedReconciliationName(arg1) {
  return window['go']['main']['App']['SuggestedReconciliationName'](arg1);
}

export function Summary(arg1) {
  return window['go']['main']['App']['Summary'](arg1);
}

export function SummaryByPeriod(arg1, arg2) {
  return window['go']['main']['App']['SummaryByPeriod'](arg1, arg2);
}

export function TaxTableInfo() {
  return window['go']['main']['App']['TaxTableInfo']();
}

export function Today() {
  return window['go']['main']['App']['Today']();
}

export function TransferEmployee(arg1) {
  return window['go']['main']['App']['TransferEmployee'](arg1);
}

export function UploadAttachment(arg1) {
  return window['go']['main']['App']['UploadAttachment'](arg1);
}

export function VATIdentity() {
  return window['go']['main']['App']['VATIdentity']();
}

export function VATPolicies() {
  return window['go']['main']['App']['VATPolicies']();
}

export function VATPolicyStatus() {
  return window['go']['main']['App']['VATPolicyStatus']();
}

export function VATReference() {
  return window['go']['main']['App']['VATReference']();
}

export function VerifyAuditLog() {
  return window['go']['main']['App']['VerifyAuditLog']();
}

export function VoidAmortization(arg1) {
  return window['go']['main']['App']['VoidAmortization'](arg1);
}

export function VoucherDetail(arg1) {
  return window['go']['main']['App']['VoucherDetail'](arg1);
}

export function VoucherMetaInfo() {
  return window['go']['main']['App']['VoucherMetaInfo']();
}

export function Vouchers(arg1) {
  return window['go']['main']['App']['Vouchers'](arg1);
}
