// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';
import {sqlite} from '../models';
import {payroll} from '../models';
import {audit} from '../models';

export function AIAgentRunStatus(arg1:string):Promise<service.AIAgentRun>;

export function AIAgentSources():Promise<Array<main.ServiceSourceOption>>;

export function AIConfig():Promise<service.AIConfig>;

export function AIPromptConfig():Promise<service.AIPromptView>;

export function AISuggest(arg1:main.AISuggestRequest):Promise<service.AISuggestResult>;

export function AISuggestions(arg1:number):Promise<Array<sqlite.SuggestionRow>>;

export function AcceptAIAgentItem(arg1:main.AIAgentItemRequest):Promise<service.AIAcceptResult>;

export function AcceptAISuggestion(arg1:main.AIAcceptRequest):Promise<service.AIAcceptResult>;

export function AccountKinds():Promise<main.AccountKindsView>;

export function AccountOptions():Promise<Array<service.AccountOption>>;

export function Accounts():Promise<service.AccountsView>;

export function ActiveContacts(arg1:string,arg2:string):Promise<Array<service.ActiveContactsView>>;

export function AdjustSalary(arg1:main.AdjustSalaryRequest):Promise<service.EmployeeView>;

export function AgingReport(arg1:main.AgingRequest):Promise<service.AgingView>;

export function AppVersion():Promise<string>;

export function ApproveClaim(arg1:main.ClaimActionRequest):Promise<service.ClaimView>;

export function AttachmentPath(arg1:string):Promise<string>;

export function Attachments(arg1:main.AttachmentQueryRequest):Promise<Array<service.AttachmentInfo>>;

export function AuditAttachments(arg1:number,arg2:number):Promise<main.AttachmentAudit>;

export function AuditLog(arg1:service.AuditQuery):Promise<main.AuditLogPage>;

export function AuditSettings():Promise<service.LogSettings>;

export function Backup(arg1:main.BackupRequest):Promise<main.backupManifestView>;

export function BankAccounts():Promise<Array<service.AccountOption>>;

export function BankFlows(arg1:main.BankFlowQueryRequest):Promise<Array<service.BankFlowView>>;

export function BankReconciliation(arg1:main.ReconciliationRequest):Promise<service.ReconciliationView>;

export function BankRules():Promise<Array<service.BankRuleView>>;

export function BankStats():Promise<service.BankStats>;

export function Bookkeeper():Promise<string>;

export function BuildPayroll(arg1:main.PayrollRunRequest):Promise<service.PayrollRunDetail>;

export function CancelAIAgentRun(arg1:string):Promise<void>;

export function CheckVoucher(arg1:main.VoucherRequest):Promise<main.VoucherCheckResult>;

export function ChooseBookDir(arg1:string):Promise<string>;

export function ChooseBookFile():Promise<string>;

export function ClaimCategories():Promise<Array<service.CategoryOption>>;

export function ClaimDetail(arg1:number):Promise<service.ClaimView>;

export function Claims(arg1:main.ClaimQueryRequest):Promise<Array<service.ClaimView>>;

export function Close(arg1:main.PeriodRequest):Promise<service.CloseResult>;

export function CloseBook():Promise<void>;

export function Columnar(arg1:main.ColumnarRequest):Promise<service.ColumnarView>;

export function ColumnarAccounts():Promise<Array<service.AccountOption>>;

export function ContactList():Promise<Array<main.ContactDetail>>;

export function ContactOptions():Promise<Array<service.ContactOption>>;

export function CreateBook(arg1:service.CreateBookInput):Promise<main.BookStatus>;

export function CreateDemoBook(arg1:number):Promise<service.DemoResult>;

export function CurrentBook():Promise<main.BookStatus>;

export function DefaultBookDir():Promise<string>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteDepartment(arg1:number):Promise<void>;

export function DeleteVoucher(arg1:number):Promise<void>;

export function DepartmentUsageOf(arg1:number):Promise<service.DepartmentUsage>;

export function Departments():Promise<Array<service.Department>>;

export function Employees(arg1:boolean):Promise<Array<service.EmployeeView>>;

export function ExportAuditLog(arg1:service.AuditQuery,arg2:string):Promise<number>;

export function ExportColumnar(arg1:main.ColumnarRequest,arg2:string):Promise<service.ColumnarExportResult>;

export function ExportReconciliation(arg1:main.ReconciliationRequest,arg2:string):Promise<service.ExportResult>;

export function ExportReport(arg1:main.ExportRequest):Promise<service.ExportResult>;

export function ExportSummary(arg1:main.SummaryRequest,arg2:string):Promise<service.SummaryExportResult>;

export function ExportVATPolicies(arg1:string):Promise<void>;

export function FilesDir():Promise<string>;

export function Health(arg1:main.PeriodRequest):Promise<service.HealthInfo>;

export function IgnoreBankFlow(arg1:number,arg2:string):Promise<void>;

export function ImportBankFlows(arg1:main.BankImportRequest):Promise<service.BankImportResult>;

export function ImportVATPolicies(arg1:string):Promise<number>;

export function InspectBackup(arg1:string):Promise<main.backupManifestView>;

export function InsuranceSchemes():Promise<Array<service.InsuranceSchemeInfo>>;

export function InvoiceCategories():Promise<Array<service.CategoryOption>>;

export function InvoiceRates():Promise<Array<service.TaxRateOption>>;

export function InvoiceSummary(arg1:string,arg2:string,arg3:string):Promise<service.InvoiceSummaryView>;

export function Invoices(arg1:main.InvoiceQueryRequest):Promise<Array<service.InvoiceView>>;

export function JudgeDeduction(arg1:service.DeductionRequest):Promise<service.DeductionView>;

export function LatestAIAgentRun():Promise<service.AIAgentRun>;

export function LedgerDetail(arg1:main.LedgerRequest):Promise<main.LedgerResult>;

export function ListBooks():Promise<main.BookList>;

export function MatchBankFlows():Promise<service.BankMatchResult>;

export function OpenBook(arg1:string):Promise<main.BookStatus>;

export function OrphanAttachments():Promise<Array<service.AttachmentInfo>>;

export function Overview():Promise<service.Dashboard>;

export function PayrollRunDetail(arg1:number):Promise<service.PayrollRunDetail>;

export function PayrollRuns():Promise<Array<service.PayrollRunView>>;

export function Periods():Promise<service.BookInfo>;

export function PostBankFlows(arg1:main.BankPostRequest):Promise<service.BankPostResult>;

export function PostClaim(arg1:main.ClaimActionRequest):Promise<service.ClaimView>;

export function PostInvoice(arg1:main.PostInvoiceRequest):Promise<service.InvoiceView>;

export function PostPayroll(arg1:number,arg2:string):Promise<service.PayrollRunDetail>;

export function PostVoucher(arg1:number,arg2:string):Promise<service.VoucherDetail>;

export function PreviewAIPrompt(arg1:string):Promise<service.AIPromptPreview>;

export function PreviewClose(arg1:main.PeriodRequest):Promise<service.ClosingPreview>;

export function RejectAIAgentItem(arg1:main.AIAgentItemRequest):Promise<void>;

export function RejectAISuggestion(arg1:main.AIAcceptRequest):Promise<void>;

export function RejectClaim(arg1:main.ClaimActionRequest):Promise<service.ClaimView>;

export function RemoveAttachment(arg1:main.RemoveAttachmentRequest):Promise<void>;

export function Reopen(arg1:main.PeriodRequest):Promise<service.ReopenResult>;

export function Report(arg1:main.ReportRequest):Promise<main.ReportResult>;

export function ResetAIPromptConfig():Promise<void>;

export function ResetVATPolicies():Promise<void>;

export function ResignEmployee(arg1:main.ResignEmployeeRequest):Promise<service.EmployeeView>;

export function ResolveVATRate(arg1:main.VATRateQuery):Promise<service.VATRateResult>;

export function RestoreBackup(arg1:main.RestoreRequest):Promise<main.RestoreResult>;

export function RevealBookDir(arg1:string):Promise<string>;

export function ReverseVoucher(arg1:main.ReverseVoucherRequest):Promise<service.VoucherDetail>;

export function SaveAIPromptConfig(arg1:service.AIPromptInput):Promise<void>;

export function SaveAIProvider(arg1:sqlite.AIProviderConfig):Promise<number>;

export function SaveAccount(arg1:service.AccountInput):Promise<service.AccountRow>;

export function SaveAndPost(arg1:main.VoucherRequest):Promise<service.VoucherDetail>;

export function SaveAuditSettings(arg1:service.LogSettings):Promise<void>;

export function SaveBankRule(arg1:main.BankRuleRequest):Promise<number>;

export function SaveBookkeeper(arg1:string):Promise<void>;

export function SaveClaim(arg1:main.ClaimRequest):Promise<service.ClaimView>;

export function SaveContact(arg1:main.ContactRequest):Promise<number>;

export function SaveDepartment(arg1:main.DepartmentRequest):Promise<number>;

export function SaveEmployee(arg1:main.EmployeeRequest):Promise<number>;

export function SaveInsuranceSchemes(arg1:Array<payroll.InsuranceScheme>):Promise<void>;

export function SaveInvoice(arg1:main.InvoiceRequest):Promise<service.InvoiceView>;

export function SaveVoucher(arg1:main.VoucherRequest):Promise<service.VoucherDetail>;

export function SchemeTemplate(arg1:string):Promise<payroll.InsuranceScheme>;

export function SetAccountEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetBankSuggestion(arg1:main.BankSuggestionRequest):Promise<service.BankFlowView>;

export function SetEnterpriseScale(arg1:string):Promise<void>;

export function SetVATStatus(arg1:main.SetVATStatusRequest):Promise<void>;

export function StartAIAgentRun(arg1:service.AIAgentRequest):Promise<service.AIAgentRun>;

export function Statement(arg1:main.StatementRequest):Promise<service.StatementView>;

export function SuggestBookPath(arg1:string):Promise<string>;

export function SuggestExportPath(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SuggestedColumnarName(arg1:string):Promise<string>;

export function SuggestedReconciliationName(arg1:string):Promise<string>;

export function Summary(arg1:main.SummaryRequest):Promise<service.SummaryView>;

export function SummaryByPeriod(arg1:number,arg2:number):Promise<service.SummaryView>;

export function TaxTableInfo():Promise<service.TaxTableInfo>;

export function Today():Promise<string>;

export function TransferEmployee(arg1:main.TransferEmployeeRequest):Promise<service.EmployeeView>;

export function UploadAttachment(arg1:main.UploadAttachmentRequest):Promise<service.AttachmentInfo>;

export function VATIdentity():Promise<service.VATIdentityInfo>;

export function VATPolicies():Promise<Array<service.VATPolicyView>>;

export function VATPolicyStatus():Promise<service.VATPolicyStatus>;

export function VATReference():Promise<service.VATReferenceInfo>;

export function VerifyAuditLog():Promise<audit.VerifyResult>;

export function VoucherDetail(arg1:number):Promise<service.VoucherDetail>;

export function VoucherMetaInfo():Promise<main.VoucherMeta>;

export function Vouchers(arg1:main.VoucherQueryRequest):Promise<Array<service.VoucherSummary>>;
